# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=50)),
                ('flag', models.IntegerField(default=0, max_length=2)),
                ('priority', models.IntegerField(default=1, max_length=2)),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'pubtime'],
            },
        ),
    ]
